### ISSUE TITLE
adata.write errors

### ISSUE THREAD

**Issue by huidongchen** [theislab/anndata#52] opened 2018-08-22 21:52 UTC
Hi guys,

I'm really enjoying the efficiency and scalability of anndata. I have been using it to manage my large datasets. Excellent work!

But unfortunately i'm having bad luck in writing adata object to  .h5ad-formatted hdf5 file. 

`adata.write(results_file)`

It takes very long time and ends up with one of the errors below (I haven't managed to store adata object in file)

1) IndexError: too many indices for array 
2)ValueError: name already used as a name or title

In adata object, I'm using different annotations including uns, obs, vars, obsm and it works smoothly without any errors. But each time i try to write it to file, the aforementioned errors are thrown out.

I will really appreciate your opinions. Thanks in advance!

**Comment by Koncopd** [comment] 2018-08-22 22:53
Hi, @huidongchen.

Do you write with sparse .X or dense?
Do you work in backed or in-memory mode?

**Comment by huidongchen** [comment] 2018-08-27 14:58
Hi ,

sorry about the slow response. I'm using dense matrix and in-memory mode.

It seems that it has something to do with 'uns' annotation. If I feed an anndata object to the unstructured annotation, when i save it, the writing process will get stuck and report error in the end.

 I'm attaching a test script here. Hope it will help.

Thanks again.
[test.ipynb.zip](https://github.com/theislab/anndata/files/2324347/test.ipynb.zip)

**Comment by huidongchen** [comment] 2018-08-28 16:00
Hi,

I'm just following up on adata.write. 'uns' annotation doesn't seemingly work for rpy2 object either. I got the following warning when trying to write adata to .h5ad-formatted hdf5 file. Is a python object required in order to write anndata object to files?

**UserWarning: Could not save field with key = "uns/X_r_obj" to hdf5 file.**

I will appreciate your help.

**Comment by falexwolf** [comment] 2018-08-28 19:33
Hi!

The line
```
adata.uns['raw'] = adata.copy()
```
is invalid. But unfortunately, this doesn't throw an error. The `.uns` attribute allows for simple data types, numpy arrays, sparse matrices and simple dictionaries.

Use the `.raw` attribute of `AnnData` for doing what you want to do
```
adata.raw = adata
```

Let me think about whether there is an easy way of testing the type upon assignment.

  Alex

**Comment by flying-sheep** [comment] 2018-08-29 06:59
well, of course there is, right?

```py
def check_simple_type(obj):
    return any(check(obj) for check in checks)

def check_simple_dict(obj):
    return isinstance(x, dict) and all(
        check_simple_type(o)
        for l in [x.keys(), x.values()]
        for o in l
    )

checks = [
    lambda x: isinstance(x, int),
    lambda x: isinstance(x, str),
    ...,
    np.isarray,
    sp.sparse.issparse,
    check_simple_dict,
]
```

**Comment by falexwolf** [comment] 2018-09-03 09:43
Yes, of course, in a custom class - but that involves subclassing OrderedDict. It might be that this is not such a trouble as for DataFrames (also for arrays it wasn't trivial, as we saw). But that's the thing to the investigation here before wrapping `.uns`'s `__setitem__` as you prototyped, right?

**Comment by huidongchen** [comment] 2018-09-10 22:38
Hi, sorry that i have to reopen the issue. I'm having some trouble again when writing anndata object to a file.

I'm using dense matrix and in-memory mode. 

When I ran `adata.write(results_file)`, i got the error ''RuntimeError: Unable to create link (message type not found)"

```
5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.link()

RuntimeError: Unable to create link (message type not found)`
```

But if I run `adata.write_loom(results_file)`, it works well.

**Comment by huidongchen** [comment] 2018-09-13 21:17
Hi Alex,

I'm sorry about the limited information. I was running a big dataset so it was a bit difficult to provide an easily reproducible script.

But I guess i finally figured it out. I stored a dictionary into anndata unstructured annotation `.uns`. One keyword contains a slash symbol `'/'` , which resulted in the error `'RuntimeError: Unable to create link (message type not found)`'`

`'repr'+'eval'` strategy (converting the dictionary to a string and ) helps solve this issue.

**Comment by falexwolf** [comment] 2018-09-17 17:03
Ah, thank you for this information! Indeed, HDF5 has problems with slashes. I'll reopen this issue so that we can print out a warning in the future.

**Comment by jorvis** [comment] 2019-01-15 14:15
I ran into this too:

```
/opt/Python-3.7.0/lib/python3.7/site-packages/anndata/readwrite/write.py:301: UserWarning: Could not save field with key = "uns/cell_type_categories" to hdf5 file.
  'to hdf5 file.'.format(key))
```

**Comment by jorvis** [comment] 2019-01-16 22:35
Mine actually happened because there were non-unicode values in the cells of the cell_type column.  Just a note.

**Comment by flying-sheep** [comment] 2019-01-21 15:13
Can you please give a reproducible example? Python does unicode by default, there should be almost no effort to fix this.

The only reason we don’t have tests for this is that I wouldn’t think it’d ever be a problem.

**Comment by jorvis** [comment] 2019-01-21 21:47
Attaching a demo dataset with test conversion script.  
[issue_52_demo.tar.gz](https://github.com/theislab/anndata/files/2780600/issue_52_demo.tar.gz)

**Comment by tantk** [comment] 2019-08-08 09:24
Hi all, i have been using scanpy library for three months now, just discovered that adata.write will give
"ValueError: name already used as a name or title" if adata.obs contains a column name 'index'. 

Just sharing in case anyone else has this problem too.

**Comment by jeffhsu3** [comment] 2020-02-12 11:01
I get a write error:
`Above error raised while writing key 0 of <class 'h5py._hl.group.Group'> from /.`
if a name of the index to the var table is an int.  Setting the name to a string fixes this.

**Comment by flying-sheep** [comment] 2020-02-12 11:51
Yeah, this is not supported. We should improve the error in this case though

**Comment by ivirshup** [comment] 2020-02-13 02:47
I'm going to close this, since new writing problems should open up new issues.

**Closed by ivirshup** 2020-02-13 02:47 UTC

**Comment by zznx** [comment] 2020-10-13 03:09
> I get a write error:
> `Above error raised while writing key 0 of <class 'h5py._hl.group.Group'> from /.`
> if a name of the index to the var table is an int. Setting the name to a string fixes this.

I have the same problem. How did you solve it?   Thanks in advance!

**Comment by yebinase** [comment] 2021-01-21 04:58
Hi, for me it has something to do with duplicated column ( or duplication between column and index), you might want to remove that
