### ISSUE TITLE
Unable to read h5ad files with h5py 2.10.0

### ISSUE THREAD

**Issue by joshua-gould** [theislab/anndata#250] opened 2019-11-15 14:51 UTC
For example, attempting to read the h5ad result file created in the scanpy tutorial pbmc3k causes the error: ValueError: invalid shape in fixed-type tuple.

**Comment by flying-sheep** [comment] 2019-11-18 10:31
Fixed in the next released. GitHub should have shown you that this is a duplicate of #235, didn’t it?

**Closed by flying-sheep** 2019-11-18 10:31 UTC

**Comment by joshua-gould** [comment] 2019-11-18 12:24
Sorry, I didn't see that this was a duplicate.

**Comment by flying-sheep** [comment] 2019-11-18 13:07
No problem! Sorry for taking so long with the anndata release, we’re almost done!

You can click on the “Watch” above and select “Releases only” to get notified!
